# -*- coding: utf-8 -*-
"""
build_daily_notes.py — parse Poor Richard's Almanack note transcripts into the
daily-note data chunk consumed by the CRM login popup.

Each aphorism in the source is a numbered Chinese line ("N. 中文") immediately
followed by an indented English line. Numbering restarts per 富心法 section, so we
assign a GLOBAL sequential id (the rotation pointer) that must stay stable across
re-runs — append new note files at the END of SOURCES so existing ids never shift.

Re-run after dropping in new transcripts:
    python build_daily_notes.py
Outputs: chunks/script-daily-note.js  (un-minified source; build.mjs makes .min)
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.abspath(__file__))

# Order matters: ids are assigned in this order. Append new files, never reorder.
SOURCES = [
    r"C:\Users\DC\Desktop\honor_notes_20260628\窮理查年鑑_筆記_20260628.txt",
]

NUM_RE = re.compile(r"^\s*(\d+)\.\s+(.*\S)\s*$")


def is_structural(line):
    s = line.strip()
    return (not s) or s.startswith("#") or s.startswith("●") or s.startswith("=") \
        or bool(NUM_RE.match(line))


def parse_file(path, notes):
    chapter = ""
    section = ""
    with open(path, encoding="utf-8") as f:
        lines = f.readlines()

    i = 0
    n = len(lines)
    while i < n:
        line = lines[i].rstrip("\n")
        s = line.strip()
        if s.startswith("## "):
            chapter = s[3:].strip()
            i += 1
            continue
        if s.startswith("### "):
            section = s[4:].strip().strip("【】").replace("】", " ").replace("【", "")
            i += 1
            continue
        m = NUM_RE.match(line)
        if m:
            zh = m.group(2).strip()
            en = ""
            # look ahead for an English continuation line (non-structural)
            j = i + 1
            while j < n and not lines[j].strip():
                j += 1
            if j < n and not is_structural(lines[j]):
                en = lines[j].strip()
            # Bilingual only: skip Chinese-only entries (e.g. 富蘭克林守則 virtues)
            if en:
                notes.append({
                    "id": len(notes) + 1,
                    "zh": zh,
                    "en": en,
                    "chapter": chapter,
                    "section": section,
                })
        i += 1


def main():
    notes = []
    for src in SOURCES:
        if not os.path.exists(src):
            print("WARN missing source:", src)
            continue
        parse_file(src, notes)

    out_path = os.path.join(ROOT, "chunks", "script-daily-note.js")
    data_json = json.dumps(notes, ensure_ascii=False, indent=0, separators=(",", ":"))

    header = (
        "// chunks/script-daily-note.js — GENERATED by build_daily_notes.py. Do not hand-edit.\n"
        "// Daily login quote data (窮理查年鑑 / Poor Richard's Almanack) + maybeShowDailyNote().\n"
        "// Re-run build_daily_notes.py to regenerate; ids are stable rotation pointers.\n"
        "(function () {\n"
        "  window.app = window.app || {};\n"
        "  var NOTES = "
    )
    footer = (
        ";\n"
        "  window.app.DAILY_NOTES = NOTES;\n"
        "\n"
        "  // Local day ordinal (device-local midnight) so 'today' matches the user's clock.\n"
        "  function dayOrdinal() {\n"
        "    var now = new Date();\n"
        "    var local = new Date(now.getFullYear(), now.getMonth(), now.getDate());\n"
        "    return Math.floor(local.getTime() / 86400000);\n"
        "  }\n"
        "  function todayKey() {\n"
        "    var d = new Date();\n"
        "    var m = ('0' + (d.getMonth() + 1)).slice(-2);\n"
        "    var day = ('0' + d.getDate()).slice(-2);\n"
        "    return d.getFullYear() + '-' + m + '-' + day;\n"
        "  }\n"
        "\n"
        "  // Same quote for everyone each day; advances by one daily; loops when exhausted.\n"
        "  window.app.getDailyNote = function () {\n"
        "    if (!NOTES.length) return null;\n"
        "    return NOTES[((dayOrdinal() % NOTES.length) + NOTES.length) % NOTES.length];\n"
        "  };\n"
        "\n"
        "  // 易经六十四卦 (I Ching) in King Wen order. HEXPY = pinyin of each name's LAST\n"
        "  // character, using the classical hexagram readings (屯 zhūn, 否 pǐ, 畜 xù, 解 xiè…).\n"
        "  var HEX = ['乾为天','坤为地','水雷屯','山水蒙','水天需','天水讼','地水师','水地比','风天小畜','天泽履','地天泰','天地否','天火同人','火天大有','地山谦','雷地豫','泽雷随','山风蛊','地泽临','风地观','火雷噬嗑','山火贲','山地剥','地雷复','天雷无妄','山天大畜','山雷颐','泽风大过','坎为水','离为火','泽山咸','雷风恒','天山遁','雷天大壮','火地晋','地火明夷','风火家人','火泽睽','水山蹇','雷水解','山泽损','风雷益','泽天夬','天风姤','泽地萃','地风升','泽水困','水风井','泽火革','火风鼎','震为雷','艮为山','风山渐','雷泽归妹','雷火丰','火山旅','巽为风','兑为泽','风水涣','水泽节','风泽中孚','雷山小过','水火既济','火水未济'];\n"
        "  var HEXPY = ['tiān','dì','zhūn','méng','xū','sòng','shī','bǐ','xù','lǚ','tài','pǐ','rén','yǒu','qiān','yù','suí','gǔ','lín','guān','hé','bì','bō','fù','wàng','xù','yí','guò','shuǐ','huǒ','xián','héng','dùn','zhuàng','jìn','yí','rén','kuí','jiǎn','xiè','sǔn','yì','guài','gòu','cuì','shēng','kùn','jǐng','gé','dǐng','léi','shān','jiàn','mèi','fēng','lǚ','fēng','zé','huàn','jié','fú','guò','jì','jì'];\n"
        "  // Hexagram of the day on an independent 64-day cycle; loops after #64.\n"
        "  window.app.getDailyHexagram = function () {\n"
        "    var i = ((dayOrdinal() % 64) + 64) % 64;\n"
        "    return { n: i + 1, name: HEX[i], py: HEXPY[i] };\n"
        "  };\n"
        "\n"
        "  // Show once per local day. Auto-closes after a delay; also has a dismiss button.\n"
        "  window.app.maybeShowDailyNote = function (force) {\n"
        "    try {\n"
        "      var key = 'daily_note_last_shown';\n"
        "      var today = todayKey();\n"
        "      if (!force && localStorage.getItem(key) === today) return;\n"
        "      var note = window.app.getDailyNote();\n"
        "      if (!note) return;\n"
        "      if (!(window.UI && UI.showModal)) return;\n"
        "      try { localStorage.setItem(key, today); } catch (e) {}\n"
        "      var esc = function (t) {\n"
        "        return String(t == null ? '' : t).replace(/[&<>\"']/g, function (c) {\n"
        "          return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;', \"'\": '&#39;' })[c];\n"
        "        });\n"
        "      };\n"
        "      var tag = esc(note.section || note.chapter || '');\n"
        "      var hx = window.app.getDailyHexagram();\n"
        "      var html = ''\n"
        "        + '<div class=\"daily-note-card\" style=\"text-align:center;padding:8px 4px 4px;\">'\n"
        "        +   '<div style=\"font-size:18px;font-weight:700;letter-spacing:.04em;color:var(--text-primary,#1c1e21);margin-bottom:18px;\">#' + hx.n + ' ' + esc(hx.name) + ' <span style=\"font-weight:500;font-style:italic;color:var(--text-secondary,#8a8f98);\">' + esc(hx.py) + '</span></div>'\n"
        "        +   '<div style=\"height:1px;background:var(--border-color,#e9ebee);margin:0 auto 18px;max-width:78%;\"></div>'\n"
        "        +   (tag ? '<div style=\"display:inline-block;font-size:12px;letter-spacing:.05em;color:var(--text-secondary,#8a8f98);border:1px solid var(--border-color,#e3e5e8);border-radius:999px;padding:3px 12px;margin-bottom:18px;\">' + tag + '</div>' : '')\n"
        "        +   '<div style=\"font-size:21px;line-height:1.6;font-weight:600;color:var(--text-primary,#1c1e21);margin-bottom:14px;\">' + esc(note.zh) + '</div>'\n"
        "        +   '<div style=\"font-size:14px;line-height:1.55;font-style:italic;color:var(--text-secondary,#6b7280);max-width:30em;margin:0 auto;\">' + esc(note.en) + '</div>'\n"
        "        +   '<div style=\"margin-top:18px;font-size:11px;color:var(--text-tertiary,#9aa0a6);\">窮理查年鑑 · Poor Richard\\'s Almanack · #' + note.id + '</div>'\n"
        "        + '</div>';\n"
        "      UI.showModal('每天一智 · Daily Wisdom', html, [\n"
        "        { label: '收到 · Got it', type: 'primary', action: 'UI.hideModal()' }\n"
        "      ]);\n"
        "      // Auto-close after 10s unless the user already dismissed it.\n"
        "      setTimeout(function () {\n"
        "        try { (window.UI && UI.hideModal) && UI.hideModal(); } catch (e) {}\n"
        "      }, 10000);\n"
        "    } catch (e) { /* never block login on the popup */ }\n"
        "  };\n"
        "})();\n"
    )

    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(header + data_json + footer)

    print("Parsed notes:", len(notes))
    print("Wrote:", out_path)
    if notes:
        print("First:", notes[0]["zh"], "/", notes[0]["en"][:40])
        print("Last :", notes[-1]["zh"], "/", notes[-1]["en"][:40])


if __name__ == "__main__":
    main()
