/**
 * CRM Lazy Chunk: cases
 * Role-gated: All roles (lazy-loaded on first nav)
 *
 * Self-contained IIFE. Accesses shared state through window.* globals only.
 * Loaded on-demand by navigateTo() role-gated chunk loader in script.js.
 * Attaches all public functions to window.app via Object.assign at the bottom.
 *
 * Generated by _extract_v2.mjs — do NOT edit the comment block above.
 */
(() => {
    // ── Live bindings to IIFE-private state ──────────────────────────────
    const _state = window._appState;
    const _utils = window._crmUtils;
    const isSystemAdmin        = (u) => _utils.isSystemAdmin(u || _state.cu);
    const isMarketingManager   = (u) => _utils.isMarketingManager(u || _state.cu);
    const isAgent              = (u) => _utils.isAgent(u || _state.cu);
    const isManagement         = (u) => _utils.isManagement(u || _state.cu);
    const isTeamLeaderOrAbove  = (u) => _utils.isTeamLeaderOrAbove(u || _state.cu);
    const isStockTakeStaff     = (u) => _utils.isStockTakeStaff(u || _state.cu);
    const escapeHtml           = (...a) => _utils.escapeHtml(...a);
    const isMobile             = () => _utils.isMobile();
    const withTimeout          = (...a) => _utils.withTimeout(...a);
    const timeAgo              = (...a) => _utils.timeAgo(...a);
    const generateId           = () => _utils.generateId();
    const debounceCall         = (...a) => window.app.debounceCall(...a);
    const navigateTo           = (v)   => window.app.navigateTo(v);
    // Cross-chunk helper — defined in script-prospects.js, exported to window.app.
    const openAddTagModal      = (...a) => (window.app.openAddTagModal || (() => {}))(...a);
    // AppDataStore, UI, supabase, XLSX (on demand) are globals — no alias needed.

    // ========== PHASE 18: CASES MODULE IMPLEMENTATION ==========

    let _caseFilters = { search: '', product: 'all', from: '', to: '', visibility: 'all', agent: 'all', tag: 'all' };
    let _caseActiveTab = 'cps'; // 'cps' | 'closed'
    let _caseAdvOpen = false;

    // React-island flag (default-on). Kill-switch → legacy: window.__REACT_CASES===false,
    // ?react=0, or localStorage crm_react_off='1'.
    const _reactCasesOn = () => {
        try {
            if (window.__REACT_CASES === false) return false;
            if (/[?&]react=0/.test(location.search)) return false;
            if (localStorage.getItem('crm_react_off') === '1') return false;
            return !!(window.CRMReact && typeof window.CRMReact.mountCasesGrid === 'function');
        } catch (_) { return false; }
    };



    // Pure HTML builder — shared filter bar (search + collapsible advanced filters).
    // Reads module-scoped _caseFilters / _caseAdvOpen / escapeHtml; takes the
    // orchestrator-local lists + count as params. No awaits / DOM mutation.
    const buildCasesFilterBar = (products, agents, allTags, activeAdvCount) => {
        return `
            <div class="cases-toolbar">
                <div class="cases-search-wrap">
                    <i class="fas fa-search cases-search-icon"></i>
                    <input type="text" id="case-search" class="cases-search-input"
                        placeholder="Search cases, prospects, customers…"
                        value="${escapeHtml(_caseFilters.search)}"
                        onkeyup="app.handleCaseSearch(event)">
                    <button class="cases-search-clear" title="Clear search"
                        onclick="document.getElementById('case-search').value=''; app.handleCaseSearch({target:{value:''}})">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
                <button id="cases-adv-toggle-btn" class="cases-filter-btn${_caseAdvOpen ? ' active' : ''}"
                    onclick="app.toggleCaseAdvFilters()">
                    <i class="fas fa-sliders-h"></i> Filters
                    ${activeAdvCount > 0 ? `<span class="cases-filter-count">${activeAdvCount}</span>` : ''}
                </button>
            </div>
            <div class="cases-adv-panel" id="cases-adv-panel" style="display:${_caseAdvOpen ? 'block' : 'none'};">
                <div class="cases-adv-grid">
                    <div class="adv-field">
                        <label>Product</label>
                        <select id="case-product-filter" onchange="app.handleCaseFilterChange()">
                            <option value="all">All Products</option>
                            ${products.map(p => `<option value="${escapeHtml(p.name)}" ${_caseFilters.product === p.name ? 'selected' : ''}>${escapeHtml(p.name)}</option>`).join('')}
                        </select>
                    </div>
                    <div class="adv-field">
                        <label>Agent</label>
                        <select id="case-agent-filter" onchange="app.handleCaseFilterChange()">
                            <option value="all">All Agents</option>
                            ${agents.map(u => `<option value="${u.id}" ${_caseFilters.agent === String(u.id) ? 'selected' : ''}>${escapeHtml(u.full_name || u.username)}</option>`).join('')}
                        </select>
                    </div>
                    <div class="adv-field">
                        <label>Date From</label>
                        <input type="date" id="case-date-from" value="${_caseFilters.from}" onchange="app.handleCaseFilterChange()">
                    </div>
                    <div class="adv-field">
                        <label>Date To</label>
                        <input type="date" id="case-date-to" value="${_caseFilters.to}" onchange="app.handleCaseFilterChange()">
                    </div>
                    <div class="adv-field">
                        <label>Tag</label>
                        <select id="case-tag-filter" onchange="app.handleCaseFilterChange()">
                            <option value="all">All Tags</option>
                            ${allTags.map(t => `<option value="${t.id}" ${_caseFilters.tag === String(t.id) ? 'selected' : ''}>${escapeHtml(t.name)}</option>`).join('')}
                        </select>
                    </div>
                    <div class="adv-field">
                        <label>Visibility</label>
                        <select id="case-visibility-filter" onchange="app.handleCaseFilterChange()">
                            <option value="all" ${_caseFilters.visibility === 'all' ? 'selected' : ''}>All</option>
                            <option value="public" ${_caseFilters.visibility === 'public' ? 'selected' : ''}>Public Only</option>
                            <option value="mine" ${_caseFilters.visibility === 'mine' ? 'selected' : ''}>My Cases</option>
                        </select>
                    </div>
                </div>
                <div class="cases-adv-footer">
                    <button class="btn-link" onclick="app.clearCaseFilters()">
                        <i class="fas fa-times-circle"></i> Clear All Filters
                    </button>
                </div>
            </div>`;
    };

    // Pure HTML builder — the cases-view shell. Interpolates the prebuilt
    // filterBar string; no awaits / DOM mutation.
    const buildCasesViewShell = (filterBar) => {
        return `
            <div class="cases-view">
                <div class="prospects-header">
                    <div>
                        <h1>Success Case Library</h1>
                        <p>Document and share success stories, sales ideas, and closing strategies.</p>
                    </div>
                    <button class="btn primary" onclick="(async () => { await app.openCaseStudyModal(); })()">
                        <i class="fas fa-plus"></i> New Case
                    </button>
                </div>

                ${filterBar}

                <!-- CPS Invitation Cases Section -->
                <div class="cases-section-hdr">
                    <div class="section-icon"><i class="fas fa-handshake"></i></div>
                    <h2>CPS Invitation Cases</h2>
                    <span class="cases-section-desc">Prospects invited via CPS method</span>
                    <span class="cases-count-pill" id="cases-count-cps">0</span>
                </div>
                <div class="case-card-grid" id="cases-list-cps"></div>
                <div id="cases-empty-state-cps" class="cases-empty-state" style="display:none;">
                    <div class="cases-empty-illus"><i class="fas fa-handshake"></i></div>
                    <h3>No CPS invitation cases yet</h3>
                    <p>Invite a prospect through CPS and they'll show up here as a case.</p>
                </div>

                <!-- Closed Cases Section -->
                <div class="cases-section-hdr" style="margin-top:40px;">
                    <div class="section-icon"><i class="fas fa-trophy"></i></div>
                    <h2>Closed Cases</h2>
                    <span class="cases-section-desc">Successfully closed deals &amp; stories</span>
                    <span class="cases-count-pill" id="cases-count-closed">0</span>
                </div>
                <div class="case-card-grid" id="cases-list-closed"></div>
                <div id="cases-empty-state-closed" class="cases-empty-state" style="display:none;">
                    <div class="cases-empty-illus"><i class="fas fa-trophy"></i></div>
                    <h3>No closed cases yet</h3>
                    <p>Document your first success story — include photos, the sales idea, and what worked.</p>
                    <button class="btn primary" onclick="(async () => { await app.openCaseStudyModal(null, 'closed'); })()">
                        <i class="fas fa-plus"></i> Add Closed Case
                    </button>
                </div>
            </div>
        `;
    };

    const showCasesView = async (container) => {
        const products = ((await AppDataStore.getAll('products')) || []).filter(p => p.is_active !== false);
        const allUsers = (await AppDataStore.getAll('users')) || [];
        const agents = allUsers.filter(u => u.status !== 'inactive');
        const allTags = (await AppDataStore.getAll('tags')) || [];

        // Count active advanced filters for badge
        const activeAdvCount = [
            _caseFilters.product !== 'all',
            _caseFilters.agent !== 'all',
            _caseFilters.from !== '',
            _caseFilters.to !== '',
            _caseFilters.tag !== 'all',
            _caseFilters.visibility !== 'all'
        ].filter(Boolean).length;

        // Shared filter bar — simple search + collapsible advanced filters
        const filterBar = buildCasesFilterBar(products, agents, allTags, activeAdvCount);

        container.innerHTML = buildCasesViewShell(filterBar);

        await renderCasesList();
    };

    // NOTE: switchCaseTab removed — the tabbed CPS/Closed UI was dropped
    // (buildCasesViewShell renders both sections together), so this had no
    // caller and was never exported. _caseActiveTab is retained as the default
    // case_type seed for openCaseStudyModal / saveCaseStudy.

    const handleCaseSearch = (e) => {
        const val = e.target.value;
        debounceCall('case-search', () => {
            _caseFilters.search = val;
            renderCasesList();
        }, 220);
    };

    const handleCaseFilterChange = async () => {
        _caseFilters.product = document.getElementById('case-product-filter')?.value || 'all';
        _caseFilters.from = document.getElementById('case-date-from')?.value || '';
        _caseFilters.to = document.getElementById('case-date-to')?.value || '';
        _caseFilters.visibility = document.getElementById('case-visibility-filter')?.value || 'all';
        _caseFilters.agent = document.getElementById('case-agent-filter')?.value || 'all';
        _caseFilters.tag = document.getElementById('case-tag-filter')?.value || 'all';
        await renderCasesList();
    };

    const toggleCaseAdvFilters = () => {
        _caseAdvOpen = !_caseAdvOpen;
        const panel = document.getElementById('cases-adv-panel');
        const btn = document.getElementById('cases-adv-toggle-btn');
        if (panel) panel.style.display = _caseAdvOpen ? 'block' : 'none';
        if (btn) btn.classList.toggle('active', _caseAdvOpen);
    };

    const clearCaseFilters = async () => {
        _caseFilters = { search: '', product: 'all', from: '', to: '', visibility: 'all', agent: 'all', tag: 'all' };
        await showCasesView(document.getElementById('content-viewport'));
    };

    const renderCasesList = async () => {
        const gridCps = document.getElementById('cases-list-cps');
        const gridClosed = document.getElementById('cases-list-closed');
        const emptyCps = document.getElementById('cases-empty-state-cps');
        const emptyClosed = document.getElementById('cases-empty-state-closed');
        const countCps = document.getElementById('cases-count-cps');
        const countClosed = document.getElementById('cases-count-closed');
        if (!gridCps || !gridClosed) return;

        // Fetch all six tables in parallel — used to be six sequential awaits
        // (3-8s on cold cache). Prospects/customers are preloaded once and
        // passed into cardModel/applySharedFilters so each card render doesn't
        // fire its own getById (was N+1 per render).
        const currentUser = _state.cu;
        const [allCases, allUsers, allTags, allTagMappings, allProspects, allCustomers] = await Promise.all([
            AppDataStore.getAll('case_studies'),
            AppDataStore.getAll('users'),
            AppDataStore.getAll('tags'),
            AppDataStore.getAll('entity_tags'),
            AppDataStore.getAll('prospects'),
            AppDataStore.getAll('customers'),
        ]).then(r => r.map(x => x || []));
        const prospectMap = new Map(allProspects.map(p => [String(p.id), p]));
        const customerMap = new Map(allCustomers.map(c => [String(c.id), c]));

        const applySharedFilters = (cases) => {
            // Visibility / permission
            cases = cases.filter(c => {
                const isOwner = c.created_by === currentUser?.id;
                const isAdmin = isSystemAdmin(currentUser) || isMarketingManager(currentUser) || /manager|team_leader/i.test(currentUser?.role || '');
                if (_caseFilters.visibility === 'public') return c.is_public;
                if (_caseFilters.visibility === 'mine') return isOwner;
                return c.is_public || isOwner || isAdmin;
            });
            // Agent
            if (_caseFilters.agent !== 'all') {
                cases = cases.filter(c => String(c.created_by) === String(_caseFilters.agent));
            }
            // Tag
            if (_caseFilters.tag !== 'all') {
                const caseIdsWithTag = allTagMappings
                    .filter(et => et.entity_type === 'case_study' && String(et.tag_id) === String(_caseFilters.tag))
                    .map(et => et.entity_id);
                cases = cases.filter(c => caseIdsWithTag.includes(c.id));
            }
            // Search — resolved against preloaded maps (was N+1 getById per case)
            if (_caseFilters.search) {
                const q = _caseFilters.search.toLowerCase();
                cases = cases.filter(c => {
                    if ((c.title || '').toLowerCase().includes(q)) return true;
                    if (c.prospect_id) {
                        const p = prospectMap.get(String(c.prospect_id));
                        if (p?.full_name?.toLowerCase().includes(q)) return true;
                    }
                    if (c.customer_id) {
                        const cust = customerMap.get(String(c.customer_id));
                        if (cust?.full_name?.toLowerCase().includes(q)) return true;
                    }
                    return false;
                });
            }
            if (_caseFilters.product !== 'all') cases = cases.filter(c => c.product === _caseFilters.product);
            // CPS invitation cases may have no closing_date — fall back to created_at
            // so the date filter doesn't silently drop them (undefined >= from is false).
            // Compare on the date-only portion (first 10 chars): created_at is a
            // full ISO timestamp, so any time-of-day on the To day would compare
            // greater than the date-only bound and be dropped otherwise.
            if (_caseFilters.from) cases = cases.filter(c => String(c.closing_date || c.created_at || '').slice(0, 10) >= _caseFilters.from);
            if (_caseFilters.to) cases = cases.filter(c => String(c.closing_date || c.created_at || '').slice(0, 10) <= _caseFilters.to);
            return cases;
        };

        const genderEmoji = (g) => {
            if (!g) return '';
            const low = String(g).toLowerCase();
            if (low.startsWith('m')) return '♂';
            if (low.startsWith('f')) return '♀';
            return '';
        };

        const productGradient = (product) => {
            const palettes = [
                'linear-gradient(135deg,#7a0018 0%,#c12b3c 100%)',
                'linear-gradient(135deg,#0f766e 0%,#14b8a6 100%)',
                'linear-gradient(135deg,#1e3a8a 0%,#3b82f6 100%)',
                'linear-gradient(135deg,#92400e 0%,#f59e0b 100%)',
                'linear-gradient(135deg,#6b21a8 0%,#a855f7 100%)',
                'linear-gradient(135deg,#065f46 0%,#10b981 100%)',
            ];
            const key = String(product || 'case');
            let hash = 0;
            for (let i = 0; i < key.length; i++) hash = (hash * 31 + key.charCodeAt(i)) >>> 0;
            return palettes[hash % palettes.length];
        };

        // React path — derive a plain, fully-computed card model from the same
        // helpers/maps the island needs to render an identical card.
        const cardModel = (c, type) => {
            let entityName = '';
            let entityIcon = '';
            let prospectData = null;
            if (c.customer_id) {
                const cust = customerMap.get(String(c.customer_id));
                if (cust) { entityName = cust.full_name; entityIcon = 'fa-user-check'; }
            } else if (c.prospect_id) {
                const pros = prospectMap.get(String(c.prospect_id));
                if (pros) { prospectData = pros; entityName = pros.full_name; entityIcon = 'fa-user'; }
            }

            const isOwner = c.created_by === currentUser?.id;
            const isAdmin = isSystemAdmin(currentUser) || isMarketingManager(currentUser) || /manager|team_leader/i.test(currentUser?.role || '');
            const canEdit = isOwner || isAdmin;

            const creator = allUsers.find(u => u.id === c.created_by);
            const creatorName = creator ? (creator.full_name || creator.username || 'Agent') : 'System';
            const creatorInitial = (creatorName[0] || '?').toUpperCase();

            const caseMappings = allTagMappings.filter(et => et.entity_type === 'case_study' && et.entity_id === c.id);
            const caseTags = caseMappings.map(mp => allTags.find(t => t.id === mp.tag_id)).filter(Boolean);
            const tags = caseTags.slice(0, 3).map(t => ({ name: t.name, bg: (t.color || '#e5e7eb'), text: (t.color || '#374151') }));
            const extraTagCount = caseTags.length > 3 ? caseTags.length - 3 : 0;

            const photos = Array.isArray(c.photo_urls) ? c.photo_urls : [];
            const coverPhoto = photos[0] || null;
            const totalPhotos = photos.length;

            const ageText = prospectData?.date_of_birth
                ? Math.floor((Date.now() - new Date(prospectData.date_of_birth)) / (365.25 * 24 * 60 * 60 * 1000)) + 'y'
                : '';

            const m = {
                id: c.id,
                type,
                coverPhoto,
                totalPhotos,
                coverGradient: productGradient(type === 'cps' ? (entityName || 'cps') : c.product),
                coverIcon: type === 'cps' ? 'fa-handshake' : 'fa-trophy',
                isPublic: !!c.is_public,
                entityName,
                entityIcon,
                canEdit,
                creatorName,
                creatorInitial,
                tags,
                extraTagCount,
            };

            if (type === 'cps') {
                m.title = entityName ? entityName : (c.title ? c.title : 'CPS Case');
                m.subtitle = prospectData?.occupation
                    ? prospectData.occupation
                    : (prospectData?.referral_relationship ? 'Referred via ' + prospectData.referral_relationship : '');
                m.desc = c.cps_invitation_details
                    ? (c.cps_invitation_details.length > 140 ? c.cps_invitation_details.substring(0, 140) + '…' : c.cps_invitation_details)
                    : 'No invitation details recorded yet.';
                m.metaPills = [
                    prospectData?.gender ? { icon: 'fa-venus-mars', text: `${prospectData.gender} ${genderEmoji(prospectData.gender)}` } : null,
                    ageText ? { icon: 'fa-birthday-cake', text: ageText } : null,
                    c.cps_invitation_method ? { icon: 'fa-paper-plane', text: c.cps_invitation_method } : null,
                    prospectData?.referral_relationship ? { icon: 'fa-people-arrows', text: prospectData.referral_relationship } : null,
                ].filter(Boolean);
            } else {
                m.title = c.title || 'Untitled Case';
                m.amountStr = c.amount ? 'RM ' + parseFloat(c.amount).toLocaleString() : '';
                const closedDate = c.closing_date ? new Date(c.closing_date).toLocaleDateString('en-MY', { year: 'numeric', month: 'short', day: 'numeric' }) : '';
                const storyPreview = (c.success_story || c.sales_idea || c.closing_details || '').trim();
                m.desc = storyPreview
                    ? (storyPreview.length > 160 ? storyPreview.substring(0, 160) + '…' : storyPreview)
                    : 'Tap to read the full closing strategy and sales idea.';
                m.metaPills = [
                    entityName ? { icon: entityIcon, text: entityName } : null,
                    c.product ? { icon: 'fa-box', text: c.product } : null,
                    closedDate ? { icon: 'fa-calendar-check', text: closedDate } : null,
                ].filter(Boolean);
            }
            return m;
        };

        const _reactOn = _reactCasesOn();

        // CPS cases — applySharedFilters + cardModel are now sync (preloaded maps)
        let cpsCases = allCases.filter(c => (c.case_type || 'cps') === 'cps');
        cpsCases = applySharedFilters(cpsCases);
        cpsCases.sort((a, b) => new Date(b.updated_at || b.created_at || 0) - new Date(a.updated_at || a.created_at || 0));
        if (countCps) countCps.textContent = cpsCases.length;
        if (_reactOn) {
            // Island owns the grid's children — never touch gridCps.innerHTML on
            // this path (it would corrupt the React root). Empty-state + grid
            // visibility are siblings, safe to toggle directly.
            try {
                const cpsModels = cpsCases.map(c => cardModel(c, 'cps'));
                window.CRMReact.mountCasesGrid(gridCps, { cards: cpsModels, type: 'cps' });
                gridCps.style.display = cpsModels.length ? '' : 'none';
                emptyCps.style.display = cpsModels.length ? 'none' : 'flex';
            } catch (e) {
                console.warn('[cases-cps] react mount failed:', e && e.message);
                if (emptyCps) emptyCps.style.display = 'none';
                gridCps.style.display = '';
                gridCps.innerHTML = '<div style="padding:48px 24px;text-align:center;color:#888;"><i class="fas fa-rotate-right" style="font-size:30px;opacity:.45;"></i><p style="margin:14px 0;">This section couldn\'t load. Please reload the page.</p><button class="btn primary" onclick="location.reload()">Reload</button></div>';
            }
        } else {
            if (emptyCps) emptyCps.style.display = 'none';
            gridCps.style.display = '';
            gridCps.innerHTML = '<div style="padding:48px 24px;text-align:center;color:#888;"><i class="fas fa-rotate-right" style="font-size:30px;opacity:.45;"></i><p style="margin:14px 0;">This section couldn\'t load. Please reload the page.</p><button class="btn primary" onclick="location.reload()">Reload</button></div>';
        }

        // Closed cases
        let closedCases = allCases.filter(c => (c.case_type || 'cps') === 'closed');
        closedCases = applySharedFilters(closedCases);
        closedCases.sort((a, b) => new Date(b.closing_date || b.updated_at || 0) - new Date(a.closing_date || a.updated_at || 0));
        if (countClosed) countClosed.textContent = closedCases.length;
        if (_reactOn) {
            try {
                const closedModels = closedCases.map(c => cardModel(c, 'closed'));
                window.CRMReact.mountCasesGrid(gridClosed, { cards: closedModels, type: 'closed' });
                gridClosed.style.display = closedModels.length ? '' : 'none';
                emptyClosed.style.display = closedModels.length ? 'none' : 'flex';
            } catch (e) {
                console.warn('[cases-closed] react mount failed:', e && e.message);
                if (emptyClosed) emptyClosed.style.display = 'none';
                gridClosed.style.display = '';
                gridClosed.innerHTML = '<div style="padding:48px 24px;text-align:center;color:#888;"><i class="fas fa-rotate-right" style="font-size:30px;opacity:.45;"></i><p style="margin:14px 0;">This section couldn\'t load. Please reload the page.</p><button class="btn primary" onclick="location.reload()">Reload</button></div>';
            }
        } else {
            if (emptyClosed) emptyClosed.style.display = 'none';
            gridClosed.style.display = '';
            gridClosed.innerHTML = '<div style="padding:48px 24px;text-align:center;color:#888;"><i class="fas fa-rotate-right" style="font-size:30px;opacity:.45;"></i><p style="margin:14px 0;">This section couldn\'t load. Please reload the page.</p><button class="btn primary" onclick="location.reload()">Reload</button></div>';
        }
    };

    const showCaseStudyDetail = async (id) => {
        const c = await AppDataStore.getById('case_studies', id);
        if (!c) return;

        const currentUser = _state.cu;
        const isOwner = c.created_by === currentUser?.id;
        const isAdmin = isSystemAdmin(currentUser) || isMarketingManager(currentUser) || /manager|team_leader/i.test(currentUser?.role || '');

        // Visibility gate — mirror applySharedFilters: a private case is readable
        // only by its owner or an admin. Without this, app.showCaseStudyDetail(id)
        // from the console would render another agent's private case.
        if (!(c.is_public || isOwner || isAdmin)) {
            UI.toast.error("Not authorized");
            return;
        }

        const isCpsCase = (c.case_type || 'cps') === 'cps';
        let entityInfo = '';
        let prospectProfile = null;
        if (c.customer_id) {
            const cust = await AppDataStore.getById('customers', c.customer_id);
            if (!isCpsCase) entityInfo = cust ? `Customer: ${cust.full_name}` : 'Unknown Customer';
        } else if (c.prospect_id) {
            const pros = await AppDataStore.getById('prospects', c.prospect_id);
            prospectProfile = pros || null;
            if (!isCpsCase) entityInfo = pros ? `Prospect: ${pros.full_name}` : 'Unknown Prospect';
        }

        const creator = await AppDataStore.getById('users', c.created_by);
        const creatorName = creator ? (creator.full_name || creator.username) : 'System';

        // Fetch tags for this case
        const allTagMappings = (await AppDataStore.getAll('entity_tags')) || [];
        const allTags = (await AppDataStore.getAll('tags')) || [];
        const caseMappings = allTagMappings.filter(et => et.entity_type === 'case_study' && et.entity_id === c.id);
        const caseTags = caseMappings.map(m => allTags.find(t => t.id === m.tag_id)).filter(Boolean);
        const tagPills = caseTags.map(t => `
            <span class="badge" style="background:${/^#[0-9a-f]{3,8}$|^[a-z]+$/i.test(String(t.color || '')) ? t.color : '#e5e7eb'};color:#1f2937;margin-right:4px;">
                ${escapeHtml(t.name)}
                <span style="cursor:pointer;margin-left:4px;" onclick="app.removeTagFromCase(${c.id}, ${t.id})">&times;</span>
            </span>`).join('');

        const typeLabel = (c.case_type || 'cps') === 'cps' ? 'CPS Invitation Case' : 'Closed Case';

        const photos = Array.isArray(c.photo_urls) ? c.photo_urls : [];
        const photoGalleryHtml = photos.length ? `
            <div class="case-detail-gallery">
                <div class="case-detail-gallery-main">
                    <img loading="lazy" decoding="async" data-attach-src="${escapeHtml(photos[0])}" alt="Cover" onclick="window._openAttachment('${UI.escJsAttr(String(photos[0]))}')">
                </div>
                ${photos.length > 1 ? `
                    <div class="case-detail-gallery-thumbs">
                        ${photos.slice(1).map(p => `<img loading="lazy" decoding="async" data-attach-src="${escapeHtml(p)}" alt="Photo" onclick="window._openAttachment('${UI.escJsAttr(String(p))}')">`).join('')}
                    </div>
                ` : ''}
            </div>
        ` : '';

        const contentHtml = `
            <div style="padding:0 4px;">
                ${photoGalleryHtml}
                <div style="display:flex;flex-wrap:wrap;gap:12px;margin-bottom:16px;color:var(--gray-500);font-size:13px;">
                    <span><i class="fas fa-tag"></i> ${typeLabel}</span>
                    ${isCpsCase ? (() => {
                        const age = prospectProfile?.date_of_birth
                            ? Math.floor((Date.now() - new Date(prospectProfile.date_of_birth)) / (365.25 * 24 * 60 * 60 * 1000)) + 'y'
                            : null;
                        return [
                            prospectProfile?.referral_relationship ? `<span><i class="fas fa-people-arrows"></i> ${escapeHtml(prospectProfile.referral_relationship)}</span>` : '',
                            prospectProfile?.occupation ? `<span><i class="fas fa-briefcase"></i> ${escapeHtml(prospectProfile.occupation)}</span>` : '',
                            age ? `<span><i class="fas fa-birthday-cake"></i> ${age}</span>` : '',
                            prospectProfile?.gender ? `<span><i class="fas fa-venus-mars"></i> ${escapeHtml(prospectProfile.gender)}</span>` : '',
                        ].filter(Boolean).join('');
                    })() : `<span><i class="fas fa-user-circle"></i> ${escapeHtml(entityInfo)}</span>
                    <span><i class="fas fa-calendar-alt"></i> Closed: ${c.closing_date || 'N/A'}</span>
                    <span><i class="fas fa-box"></i> ${escapeHtml(c.product || 'N/A')}</span>
                    <span><i class="fas fa-money-bill-wave"></i> RM ${parseFloat(c.amount || 0).toLocaleString()}</span>`}
                    ${c.is_public ? '<span class="badge badge-success">Public</span>' : ''}
                </div>

                <div style="margin-bottom:16px;">
                    <strong style="font-size:12px;color:var(--gray-500);text-transform:uppercase;letter-spacing:.05em;">Tags</strong>
                    <div style="margin-top:6px;">
                        ${tagPills || '<em style="color:var(--gray-400);font-size:13px;">No tags</em>'}
                        <button class="btn secondary btn-sm" style="margin-left:8px;" onclick="app.addTagToCase(${c.id})"><i class="fas fa-tag"></i> Add Tag</button>
                    </div>
                </div>

                <div class="case-section card" style="margin-bottom:12px;">
                    <h3 style="font-size:14px;font-weight:600;margin-bottom:8px;"><i class="fas fa-handshake"></i> Part 1: CPS Invitation</h3>
                    ${c.cps_invitation_method ? `<p style="font-size:12px;color:var(--gray-500);margin-bottom:6px;"><strong>Method:</strong> ${escapeHtml(c.cps_invitation_method)}</p>` : ''}
                    <p style="white-space:pre-wrap;">${c.cps_invitation_details ? escapeHtml(c.cps_invitation_details) : '<em style="color:var(--gray-400);">No details provided.</em>'}</p>
                </div>

                <div class="case-section card" style="margin-bottom:12px;">
                    <h3 style="font-size:14px;font-weight:600;margin-bottom:12px;"><i class="fas fa-check-double"></i> Part 2: Closing & Strategy</h3>
                    <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;">
                        <div>
                            <h4 style="font-size:12px;font-weight:600;color:var(--gray-500);text-transform:uppercase;margin-bottom:4px;">Closing Details</h4>
                            <p style="white-space:pre-wrap;">${escapeHtml(c.closing_details || '-')}</p>
                        </div>
                        <div>
                            <h4 style="font-size:12px;font-weight:600;color:var(--gray-500);text-transform:uppercase;margin-bottom:4px;">The Sales Idea</h4>
                            <p style="white-space:pre-wrap;">${escapeHtml(c.sales_idea || '-')}</p>
                        </div>
                        <div>
                            <h4 style="font-size:12px;font-weight:600;color:var(--gray-500);text-transform:uppercase;margin-bottom:4px;">Execution Plan</h4>
                            <p style="white-space:pre-wrap;">${escapeHtml(c.plan_details || '-')}</p>
                        </div>
                        <div>
                            <h4 style="font-size:12px;font-weight:600;color:var(--gray-500);text-transform:uppercase;margin-bottom:4px;">Success Story & Lessons</h4>
                            <p style="white-space:pre-wrap;">${escapeHtml(c.success_story || '-')}</p>
                        </div>
                    </div>
                </div>

                ${(c.key_success_factor || c.script) ? `
                <div class="case-section card" style="margin-bottom:12px;">
                    <h3 style="font-size:14px;font-weight:600;margin-bottom:12px;"><i class="fas fa-star"></i> Part 3: Key Factors & Script</h3>
                    ${c.key_success_factor ? `
                    <div style="margin-bottom:12px;">
                        <h4 style="font-size:12px;font-weight:600;color:var(--gray-500);text-transform:uppercase;margin-bottom:4px;">Key Success Factor</h4>
                        <p style="white-space:pre-wrap;">${escapeHtml(c.key_success_factor)}</p>
                    </div>` : ''}
                    ${c.script ? `
                    <div>
                        <h4 style="font-size:12px;font-weight:600;color:var(--gray-500);text-transform:uppercase;margin-bottom:4px;">Sales Script</h4>
                        <div style="background:var(--gray-50);border:1px solid var(--gray-200);border-radius:6px;padding:12px;">
                            <p style="white-space:pre-wrap;font-family:monospace;font-size:13px;">${escapeHtml(c.script)}</p>
                        </div>
                    </div>` : ''}
                </div>` : ''}

                <div style="font-size:12px;color:var(--gray-400);margin-top:8px;">
                    <span>Created by <strong>${escapeHtml(creatorName)}</strong> on ${new Date(c.created_at).toLocaleDateString()}</span>
                    ${c.updated_at ? ` &middot; Updated ${new Date(c.updated_at).toLocaleString()}` : ''}
                </div>
            </div>
        `;

        const footerButtons = [
            { label: 'Close', type: 'secondary', action: 'UI.hideModal()' },
            { label: 'Copy Link', type: 'secondary', action: `app.copyCaseLink(${c.id})` },
            ...(isOwner || isAdmin ? [
                { label: c.is_public ? 'Make Private' : 'Share Publicly', type: 'secondary', action: `(async () => { await app.toggleCasePublic(${c.id}); })()` },
                { label: 'Edit', type: 'secondary', action: `UI.hideModal(); app.openCaseStudyModal(${c.id})` },
                { label: 'Delete', type: 'danger', action: `(async () => { await app.deleteCaseStudy(${c.id}); UI.hideModal(); })()` }
            ] : [])
        ];

        UI.showModal(c.title, contentHtml, footerButtons);
    };

    const toggleCasePublic = async (id) => {
        const c = await AppDataStore.getById('case_studies', id);
        if (!c) return;
        // Only the owner or an admin may change a case's visibility.
        const currentUser = _state.cu;
        const isOwner = c.created_by === currentUser?.id;
        const isAdmin = isSystemAdmin(currentUser) || isMarketingManager(currentUser) || /manager|team_leader/i.test(currentUser?.role || '');
        if (!(isOwner || isAdmin)) { UI.toast.error("Not authorized"); return; }
        await AppDataStore.update('case_studies', id, { is_public: !c.is_public });
        UI.toast.success(`Case study is now ${!c.is_public ? 'public' : 'private'}.`);
        await showCaseStudyDetail(id);
    };

    const copyCaseLink = (id) => {
        const link = `${window.location.origin}${window.location.pathname}?view=cases&id=${id}`;
        navigator.clipboard.writeText(link).then(() => {
            UI.toast.info("Link copied to clipboard.");
        }).catch(() => {
            UI.toast.error("Couldn't copy link — copy it manually: " + link);
        });
    };

    const deleteCaseStudy = async (id) => {
        // Read row first so we know which photos to clean up from Storage — and
        // so we can gate the delete to the owner or an admin.
        const c = await AppDataStore.getById('case_studies', id).catch(() => null);
        if (!c) return;
        const currentUser = _state.cu;
        const isOwner = c.created_by === currentUser?.id;
        const isAdmin = isSystemAdmin(currentUser) || isMarketingManager(currentUser) || /manager|team_leader/i.test(currentUser?.role || '');
        if (!(isOwner || isAdmin)) { UI.toast.error("Not authorized"); return; }
        if (confirm("Are you sure you want to delete this case? This action cannot be undone.")) {
            try {
                const photoUrls = c && Array.isArray(c.photo_urls) ? c.photo_urls : [];

                const tags = await AppDataStore.getAll('entity_tags').catch(() => []);
                for (const t of tags.filter(t => t.entity_type === 'case_study' && String(t.entity_id) === String(id)))
                    await AppDataStore.delete('entity_tags', t.id);
                await AppDataStore.delete('case_studies', id);

                // Cascade-delete the photo objects from the `attachments`
                // bucket so we don't leak orphaned files. Best-effort —
                // failures here don't roll back the row deletion.
                if (photoUrls.length && AppDataStore.deleteAttachmentByPath && AppDataStore.extractAttachmentPath) {
                    for (const url of photoUrls) {
                        const path = AppDataStore.extractAttachmentPath(url);
                        if (path) await AppDataStore.deleteAttachmentByPath(path);
                    }
                }

                UI.toast.success("Case deleted.");
                await renderCasesList();
            } catch (err) {
                UI.toast.error('Delete failed: ' + (err.message || 'Unknown error'));
            }
        }
    };

    const addTagToCase = (caseId) => {
        openAddTagModal(caseId, 'case_study');
    };

    const removeTagFromCase = async (caseId, tagId) => {
        const mappings = await AppDataStore.query('entity_tags', { entity_type: 'case_study', entity_id: caseId, tag_id: tagId });
        if (mappings?.length) {
            await AppDataStore.delete('entity_tags', mappings[0].id);
            UI.toast.success('Tag removed');
            await showCaseStudyDetail(caseId);
        }
    };

    let _casePendingPhotos = [];

    const openCaseStudyModal = async (id = null, defaultType = null) => {
        const c = id ? await AppDataStore.getById('case_studies', id) : null;
        const title = id ? 'Edit Case' : 'New Case';
        const caseType = c ? (c.case_type || 'cps') : (defaultType || _caseActiveTab || 'cps');

        _casePendingPhotos = c && Array.isArray(c.photo_urls) ? [...c.photo_urls] : [];

        let entityName = '';
        if (c) {
            if (c.customer_id) {
                const cust = await AppDataStore.getById('customers', c.customer_id);
                entityName = cust ? cust.full_name : '';
            } else if (c.prospect_id) {
                const pros = await AppDataStore.getById('prospects', c.prospect_id);
                entityName = pros ? pros.full_name : '';
            }
        }

        const modalHtml = `
            <div class="case-study-form">
                <input type="hidden" id="case-type" value="${caseType}">
                <div class="modal-tabs">
                    <button class="tab-btn active" onclick="app.switchModalTab(event, 'basic')">Basic Info</button>
                    <button class="tab-btn" onclick="app.switchModalTab(event, 'cps')">CPS Invitation</button>
                    <button class="tab-btn" onclick="app.switchModalTab(event, 'closing')">Closing & Success</button>
                </div>

                <div id="case-tab-basic" class="modal-tab-content active">
                    <div class="form-group">
                        <label>Title <span class="required">*</span></label>
                        <input type="text" id="case-title" class="form-control" value="${c ? escapeHtml(c.title) : ''}" placeholder="e.g. How I closed PR4 with career focus">
                    </div>

                    <div class="form-row">
                        <div class="form-group half">
                            <label>Link Prospect/Customer</label>
                            <div class="search-select-container">
                                <input type="text" id="case-entity-search" class="form-control" placeholder="Type name..." value="${escapeHtml(entityName)}" onkeyup="app.debounceCall('case-entity-search', () => app.searchCaseEntities(this.value), 220)">
                                <div id="case-entity-results" class="search-results-dropdown"></div>
                                <input type="hidden" id="case-prospect-id" value="${c ? (c.prospect_id || '') : ''}">
                                <input type="hidden" id="case-customer-id" value="${c ? (c.customer_id || '') : ''}">
                            </div>
                        </div>
                        <div class="form-group half">
                            <label>Product</label>
                            <select id="case-product" class="form-control">
                                <option value="">Select Product...</option>
                                ${((await AppDataStore.getAll('products')) || []).map(p => `<option value="${escapeHtml(p.name)}" ${c && c.product === p.name ? 'selected' : ''}>${escapeHtml(p.name)}</option>`).join('')}
                            </select>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group half">
                            <label>Amount (RM)</label>
                            <input type="number" id="case-amount" class="form-control" value="${c ? c.amount : ''}" placeholder="0.00">
                        </div>
                        <div class="form-group half">
                            <label>Closing Date</label>
                            <input type="date" id="case-closing-date" class="form-control" value="${c ? c.closing_date : new Date().toISOString().split('T')[0]}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label><i class="fas fa-camera"></i> Photos</label>
                        <p class="help-text">Add event photos, testimonials, or product shots — the first photo becomes the cover.</p>
                        <div class="case-photo-uploader">
                            <div id="case-photo-gallery" class="case-photo-gallery"></div>
                            <label class="case-photo-add" for="case-photo-input">
                                <i class="fas fa-plus"></i>
                                <span>Add Photo</span>
                                <input type="file" id="case-photo-input" accept="image/*" multiple hidden onchange="app.uploadCasePhotos(event)">
                            </label>
                        </div>
                    </div>
                </div>

                <div id="case-tab-cps" class="modal-tab-content">
                    <div class="form-group">
                        <label>CPS Invitation Details</label>
                        <p class="help-text">Who invited? Call/Event/Referral? Special circumstances?</p>
                        <textarea id="case-cps-details" class="form-control" rows="8">${c ? escapeHtml(c.cps_invitation_details || '') : ''}</textarea>
                    </div>
                </div>

                <div id="case-tab-closing" class="modal-tab-content">
                    <div class="form-group">
                        <label>Closing Details</label>
                        <textarea id="case-closing-details" class="form-control" rows="3" placeholder="Key discussions, objections overcome...">${c ? escapeHtml(c.closing_details || '') : ''}</textarea>
                    </div>
                    <div class="form-group">
                        <label>The Sales Idea</label>
                        <textarea id="case-sales-idea" class="form-control" rows="3" placeholder="The core logic that worked...">${c ? escapeHtml(c.sales_idea || '') : ''}</textarea>
                    </div>
                    <div class="form-group">
                        <label>Plan Details</label>
                        <textarea id="case-plan-details" class="form-control" rows="3" placeholder="Follow-up sequence, bundling...">${c ? escapeHtml(c.plan_details || '') : ''}</textarea>
                    </div>
                    <div class="form-group">
                        <label>Overall Success Story</label>
                        <textarea id="case-success-story" class="form-control" rows="3" placeholder="Testimonial, lessons learned...">${c ? escapeHtml(c.success_story || '') : ''}</textarea>
                    </div>
                    <div class="form-group">
                        <label>Key Success Factor</label>
                        <textarea id="case-key-success-factor" class="form-control" rows="3" placeholder="The single most important factor that made this case succeed...">${c ? escapeHtml(c.key_success_factor || '') : ''}</textarea>
                    </div>
                    <div class="form-group">
                        <label>Sales Script</label>
                        <textarea id="case-script" class="form-control" rows="4" placeholder="The exact words, pitch, or script that worked...">${c ? escapeHtml(c.script || '') : ''}</textarea>
                    </div>
                </div>
            </div>
        `;

        UI.showModal(title, modalHtml, [
            { label: 'Cancel', type: 'secondary', action: 'UI.hideModal()' },
            { label: id ? 'Update Case' : 'Save Case', type: 'primary', action: `(async () => { await app.saveCaseStudy(${id || 'null'}); })()` }
        ]);

        renderCasePhotoGallery();
    };

    const renderCasePhotoGallery = () => {
        const gal = document.getElementById('case-photo-gallery');
        if (!gal) return;
        if (!_casePendingPhotos.length) {
            gal.innerHTML = '<div class="case-photo-empty"><i class="fas fa-images"></i> No photos yet — add up to 12 to tell the story visually.</div>';
            return;
        }
        gal.innerHTML = _casePendingPhotos.map((url, i) => `
            <div class="case-photo-thumb" draggable="false">
                <img loading="lazy" decoding="async" data-attach-src="${escapeHtml(url)}" alt="Case photo ${i + 1}" onclick="window._openAttachment('${UI.escJsAttr(String(url))}')">
                ${i === 0 ? '<span class="case-photo-badge">Cover</span>' : ''}
                <button class="case-photo-remove" title="Remove" onclick="event.stopPropagation(); app.removeCasePhoto(${i})"><i class="fas fa-times"></i></button>
            </div>
        `).join('');
    };

    const uploadCasePhotos = async (event) => {
        const files = Array.from(event.target?.files || []);
        if (!files.length) return;
        const sb = window.supabase || window.supabaseClient;
        if (!sb || !sb.storage) { UI.toast.error('Supabase not connected — cannot upload photo'); return; }

        const addBtn = document.querySelector('.case-photo-add');
        const originalHtml = addBtn ? addBtn.innerHTML : '';
        if (addBtn) addBtn.innerHTML = '<i class="fas fa-spinner fa-spin"></i><span>Uploading…</span>';

        let uploaded = 0, failed = 0;
        for (const file of files) {
            if (!/^image\//.test(file.type)) { failed++; continue; }
            if (file.size > 8 * 1024 * 1024) {
                UI.toast.error(`"${file.name}" is larger than 8MB — skipped`);
                failed++;
                continue;
            }
            try {
                const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, '_');
                const path = `case_photos/${_state.cu?.id || 'anon'}_${Date.now()}_${Math.random().toString(36).slice(2,8)}_${safeName}`;
                const { error: upErr } = await sb.storage.from('attachments').upload(path, file, { upsert: false, contentType: file.type });
                if (upErr) throw upErr;
                const { data: urlData } = sb.storage.from('attachments').getPublicUrl(path);
                if (!urlData?.publicUrl) throw new Error('Could not resolve public URL');
                _casePendingPhotos.push(urlData.publicUrl);
                uploaded++;
            } catch (err) {
                console.error('Case photo upload failed:', err);
                failed++;
            }
        }

        if (addBtn) addBtn.innerHTML = originalHtml;
        const input = document.getElementById('case-photo-input');
        if (input) input.value = '';

        if (uploaded) UI.toast.success(`${uploaded} photo${uploaded > 1 ? 's' : ''} uploaded`);
        if (failed) UI.toast.error(`${failed} upload${failed > 1 ? 's' : ''} failed`);
        renderCasePhotoGallery();
    };

    const removeCasePhoto = (index) => {
        if (index < 0 || index >= _casePendingPhotos.length) return;
        _casePendingPhotos.splice(index, 1);
        renderCasePhotoGallery();
    };

    const switchModalTab = (e, tabId) => {
        document.querySelectorAll('.tab-btn').forEach(btn => btn.classList.remove('active'));
        document.querySelectorAll('.modal-tab-content').forEach(content => content.classList.remove('active'));

        e.target.classList.add('active');
        document.getElementById(`case-tab-${tabId}`).classList.add('active');
    };

    const searchCaseEntities = async (query) => {
        const results = document.getElementById('case-entity-results');
        if (!results) return;
        if (!query || query.length < 2) {
            results.style.display = 'none';
            return;
        }

        const [allP, allC] = await Promise.all([
            AppDataStore.getAll('prospects'),
            AppDataStore.getAll('customers'),
        ]);
        const q = query.toLowerCase();
        const prospects = (allP || []).filter(p => p.full_name?.toLowerCase().includes(q) || p.nickname?.toLowerCase().includes(q)).slice(0, 30);
        const customers = (allC || []).filter(c => c.full_name?.toLowerCase().includes(q) || c.nickname?.toLowerCase().includes(q)).slice(0, 30);

        let html = '';
        if (prospects.length > 0) {
            html += '<div class="search-category">Prospects</div>';
            html += prospects.map(p => `<div class="search-result-item" onclick="app.selectCaseEntity('${p.id}', 'prospect', '${UI.escJsAttr(p.full_name)}')">${escapeHtml(p.full_name)}</div>`).join('');
        }
        if (customers.length > 0) {
            html += '<div class="search-category">Customers</div>';
            html += customers.map(c => `<div class="search-result-item" onclick="app.selectCaseEntity('${c.id}', 'customer', '${UI.escJsAttr(c.full_name)}')">${escapeHtml(c.full_name)}</div>`).join('');
        }

        if (html === '') {
            html = '<div class="p-2 text-center text-muted">No results found</div>';
        }

        results.innerHTML = html;
        results.style.display = 'block';
    };

    const selectCaseEntity = (id, type, name) => {
        document.getElementById('case-entity-search').value = name;
        document.getElementById('case-prospect-id').value = type === 'prospect' ? id : '';
        document.getElementById('case-customer-id').value = type === 'customer' ? id : '';
        document.getElementById('case-entity-results').style.display = 'none';
    };

    const saveCaseStudy = async (id) => {
        const title = document.getElementById('case-title').value.trim();
        if (!title) {
            UI.toast.error("Title is required.");
            return;
        }

        const data = {
            title,
            case_type: document.getElementById('case-type')?.value || _caseActiveTab,
            prospect_id: document.getElementById('case-prospect-id').value || null,
            customer_id: document.getElementById('case-customer-id').value || null,
            product: document.getElementById('case-product').value,
            amount: parseFloat(document.getElementById('case-amount').value) || 0,
            closing_date: document.getElementById('case-closing-date').value,
            cps_invitation_details: document.getElementById('case-cps-details').value,
            closing_details: document.getElementById('case-closing-details').value,
            sales_idea: document.getElementById('case-sales-idea').value,
            plan_details: document.getElementById('case-plan-details').value,
            success_story: document.getElementById('case-success-story').value,
            key_success_factor: document.getElementById('case-key-success-factor').value,
            script: document.getElementById('case-script').value,
            photo_urls: Array.isArray(_casePendingPhotos) ? _casePendingPhotos : [],
            updated_at: new Date().toISOString()
        };
        const photos = Array.isArray(_casePendingPhotos) ? _casePendingPhotos : [];

        if (id) {
            // On UPDATE: preserve the stored is_public — do NOT re-derive it.
            // Auto-deriving here silently re-publishes a case the owner made
            // private via toggleCasePublic. Privacy is changed only through
            // the dedicated Make Private / Share Publicly control.
            await AppDataStore.update('case_studies', id, data);
            UI.toast.success("Case updated.");
        } else {
            // On CREATE only: seed is_public from whether any shareable content exists.
            data.is_public = !!(
                data.cps_invitation_details?.trim() ||
                data.closing_details?.trim() ||
                data.sales_idea?.trim() ||
                data.plan_details?.trim() ||
                data.success_story?.trim() ||
                data.key_success_factor?.trim() ||
                data.script?.trim() ||
                photos.length > 0
            );
            // Never fabricate ownership from a dead/expired session (audit #392/#425):
            // a hardcoded created_by=1 corrupts ownership/RLS and hides the case
            // from its real author. Block the create instead.
            if (!_state.cu?.id) {
                UI.toast.error("Session expired, please re-login.");
                return;
            }
            data.created_by = _state.cu.id;
            data.created_at = new Date().toISOString();
            const newCase = await AppDataStore.create('case_studies', data);
            UI.toast.success("Case created.");
            id = newCase.id;
        }

        UI.hideModal();
        await renderCasesList();
    };
    // ── Register public surface on window.app ────────────────────────────
    // Complete list of top-level definitions in this chunk (scanned by
    // _patch_v2.mjs — includes column-0 definitions the extractor missed).
    app.register('cases', {
        handleCaseSearch,
        toggleCaseAdvFilters,
        handleCaseFilterChange,
        clearCaseFilters,
        openCaseStudyModal,
        showCaseStudyDetail,
        deleteCaseStudy,
        removeTagFromCase,
        addTagToCase,
        copyCaseLink,
        toggleCasePublic,
        switchModalTab,
        searchCaseEntities,
        uploadCasePhotos,
        saveCaseStudy,
        removeCasePhoto,
        selectCaseEntity,
        showCasesView,
    });
})();
