-- =============================================================================
-- customer_improvements_2026-08-15.sql
-- 改命后的进步 (Customer Improvement Log)
--
-- Per-customer improvement records (date + solution used + story) shown in a new
-- accordion section on the customer profile, with a full-screen 回顾 (story mode)
-- for reviewing the journey with the customer.
--
-- Also authors public.customer_is_visible(bigint) — the customer analogue of
-- prospect_is_visible (sec_2026-06-19_pii_tables.sql) — reusable by any future
-- customer child table. RLS from day one (pipeline_v7 lesson).
--
-- Scoping:
--   SELECT  = anyone who can see the customer (mirrors customers_scoped_select)
--   WRITE   = the customer's responsible agent OR management (level <= 4)
-- =============================================================================

create table if not exists public.customer_improvements (
  id           bigint generated by default as identity primary key,
  customer_id  bigint not null references public.customers(id) on delete cascade,
  improve_date date not null,
  solution     text,
  story        text not null,
  created_by   bigint references public.users(id),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists customer_improvements_customer_idx
  on public.customer_improvements (customer_id);

-- updated_at touch (generic fn from scale_30k_1k_2026-04-25.sql)
drop trigger if exists trg_customer_improvements_updated_at on public.customer_improvements;
create trigger trg_customer_improvements_updated_at
  before update on public.customer_improvements
  for each row execute function public.set_updated_at();

-- Visibility helper: same predicate as customers_scoped_select
-- (rls_select_scoping_APPLIED_2026-06-18.sql:49-54), packaged for child tables.
-- search_path pins pg_temp per the prospect_is_visible precedent
-- (sec_2026-06-19_pii_tables.sql) — SECDEF shadowing hygiene.
create or replace function public.customer_is_visible(cid bigint)
returns boolean
language sql stable security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.customers c
    where c.id = cid
      and (
        c.responsible_agent_id in (select public.current_user_visible_ids())
        or c.responsible_agent_id = public.current_user_row_id()
        or (c.responsible_agent_id is null and coalesce(public.current_user_level(), 99) <= 2)
      )
  );
$$;

revoke all on function public.customer_is_visible(bigint) from public;
grant execute on function public.customer_is_visible(bigint) to authenticated, service_role;

-- Write test: responsible agent for this customer, or management (level <= 4)
-- WITHIN their visible subtree (L1/L2 see everyone via current_user_visible_ids,
-- so their reach is unchanged; L3/L4 cannot write to customers they cannot see).
create or replace function public.customer_improvement_can_write(cid bigint)
returns boolean
language sql stable security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.customers c
    where c.id = cid
      and (
        c.responsible_agent_id = public.current_user_row_id()
        or (coalesce(public.current_user_level(), 99) <= 4 and public.customer_is_visible(c.id))
      )
  );
$$;

revoke all on function public.customer_improvement_can_write(bigint) from public;
grant execute on function public.customer_improvement_can_write(bigint) to authenticated, service_role;

alter table public.customer_improvements enable row level security;

drop policy if exists cimp_select_scoped on public.customer_improvements;
create policy cimp_select_scoped on public.customer_improvements
  for select to authenticated
  using (public.customer_is_visible(customer_id));

-- created_by is pinned to the caller (or null) so attribution can't be forged;
-- the freeze trigger below stops later rewrites via UPDATE.
drop policy if exists cimp_insert_scoped on public.customer_improvements;
create policy cimp_insert_scoped on public.customer_improvements
  for insert to authenticated
  with check (
    public.customer_improvement_can_write(customer_id)
    and (created_by is null or created_by = public.current_user_row_id())
  );

create or replace function public.cimp_freeze_created_by()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.created_by := old.created_by;
  return new;
end;
$$;

drop trigger if exists trg_cimp_freeze_created_by on public.customer_improvements;
create trigger trg_cimp_freeze_created_by
  before update on public.customer_improvements
  for each row execute function public.cimp_freeze_created_by();

drop policy if exists cimp_update_scoped on public.customer_improvements;
create policy cimp_update_scoped on public.customer_improvements
  for update to authenticated
  using (public.customer_improvement_can_write(customer_id))
  with check (public.customer_improvement_can_write(customer_id));

drop policy if exists cimp_delete_scoped on public.customer_improvements;
create policy cimp_delete_scoped on public.customer_improvements
  for delete to authenticated
  using (public.customer_improvement_can_write(customer_id));

-- Belt-and-suspenders (default privileges already cover new tables; anon gets nothing).
grant select, insert, update, delete on public.customer_improvements to authenticated;
grant all on public.customer_improvements to service_role;

notify pgrst, 'reload schema';
