-- 汇集 Event Briefing — house owner + verified purchased solutions (2026-08-15)
-- A 汇集 event is a visit to an existing customer's house. This child table holds
-- the private briefing: whose house + which purchased solutions were verified for
-- showcase. It is a SEPARATE table (not columns on `events`) because events rows
-- are world-readable and RLS is row-level — visibility here must be restricted.
--
-- Visibility (owner decision 2026-08-15):
--   READ   = creator OR management chain level<=5 (L1/L2/L4/L5 Team Leader)
--   WRITE  = creator only (managers are view-only)
-- Helpers: public.current_user_row_id() maps auth.uid()->users.id;
--          public.current_user_level() is the ONE canonical role parser.
-- `solutions` jsonb items: {label, date, purchase_id|null, source: purchase|conversion|manual}
-- Deliberately price-free: amounts are never stored here.

create table if not exists public.event_huiji_details (
  id                bigint generated by default as identity primary key,
  event_id          bigint not null unique references public.events(id) on delete cascade,
  owner_customer_id bigint not null references public.customers(id),
  solutions         jsonb  not null default '[]'::jsonb,
  notes             text,
  created_by        bigint not null references public.users(id),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index if not exists idx_ehd_owner on public.event_huiji_details(owner_customer_id);

alter table public.event_huiji_details enable row level security;

drop policy if exists ehd_select on public.event_huiji_details;
create policy ehd_select on public.event_huiji_details
  for select to authenticated
  using (
    created_by = public.current_user_row_id()
    or coalesce(public.current_user_level(), 99) <= 5
  );

drop policy if exists ehd_insert on public.event_huiji_details;
create policy ehd_insert on public.event_huiji_details
  for insert to authenticated
  with check (created_by = public.current_user_row_id());

drop policy if exists ehd_update on public.event_huiji_details;
create policy ehd_update on public.event_huiji_details
  for update to authenticated
  using      (created_by = public.current_user_row_id())
  with check (created_by = public.current_user_row_id());

drop policy if exists ehd_delete on public.event_huiji_details;
create policy ehd_delete on public.event_huiji_details
  for delete to authenticated
  using (created_by = public.current_user_row_id());
