-- =====================================================================
-- pipeline_v7_2026-07-31.sql — Pipeline v7 (PIPELINE_V7_PLAN.md)
-- Additive only; pre-authorized class.
--
-- 1) activities.outcome — typed meeting result feeding negative signals:
--    'positive' | 'neutral' | 'negative' | 'not_interested'.
--    DELIBERATELY NO CHECK CONSTRAINT: AppDataStore's strip-and-retry only
--    handles 42703 (unknown column); a 23514 CHECK violation would fail the
--    whole activity save instead of one field (2026-07-29 lesson).
--
-- 2) pipeline_snapshots — daily calibration dataset. One row per qualified
--    prospect per user per day (client throttles to one bulk insert/day;
--    the UNIQUE constraint rejects same-day dupes from a second device).
--    RLS from day one (approval_queue M8 lesson — never scope later):
--      INSERT: own rows (user_id = current_user_row_id()) or admin L1-2
--      SELECT: own rows or admin L1-2
--    current_user_row_id() / current_user_level() are the established helpers
--    (sec_2026-06-19_writes.sql).
-- =====================================================================

alter table public.activities add column if not exists outcome text;

create table if not exists public.pipeline_snapshots (
  id bigint generated by default as identity primary key,
  snapped_at date not null default current_date,
  user_id bigint not null,
  prospect_id bigint not null,
  probability integer not null default 0,
  raw_score numeric,
  category text,
  stage text,
  fit integer,
  from_potential boolean not null default false,
  potential_level text,
  created_at timestamptz not null default now(),
  unique (snapped_at, user_id, prospect_id)
);

create index if not exists idx_plsnap_prospect on public.pipeline_snapshots (prospect_id, snapped_at);
create index if not exists idx_plsnap_user_date on public.pipeline_snapshots (user_id, snapped_at);

alter table public.pipeline_snapshots enable row level security;

drop policy if exists plsnap_insert_own on public.pipeline_snapshots;
create policy plsnap_insert_own on public.pipeline_snapshots
  for insert to authenticated
  with check (
    user_id = public.current_user_row_id()
    or coalesce(public.current_user_level(), 99) <= 2
  );

drop policy if exists plsnap_select_scoped on public.pipeline_snapshots;
create policy plsnap_select_scoped on public.pipeline_snapshots
  for select to authenticated
  using (
    user_id = public.current_user_row_id()
    or coalesce(public.current_user_level(), 99) <= 2
  );

notify pgrst, 'reload schema';

-- Verify:
--   GET /rest/v1/activities?select=outcome&limit=1          → 200
--   GET /rest/v1/pipeline_snapshots?select=id&limit=1       → 200 (as authed)
